### ISSUE TITLE
Remove the feature to submit code to Codeforces

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/api-client#127]
I decided to remove the feature to submit code to Codeforces. It's already broken (https://github.com/online-judge-tools/api-client/issues/117), and I will not fix it.

There is three reasons. The feature is:

1.  ethically unrecommended
2.  technically difficult
3.  not so beneficial for our users

I don't want to maintain such a feature. Rather, I would like to focus more beneficial and interesting tasks, e.g. automatically analyzing problems and generating solutions ([online-judge-tools/template-generator](https://github.com/online-judge-tools/template-generator), [kmyk/Jikka](https://github.com/kmyk/Jikka)).

Of course I'll merge it if someone implement the feature appropriately and send it as a pull request. However I, @kmyk, won't implement it.

## 1. ethics

The submission feature is basically not welcomed by online judges, because such a feature can easily cause trouble.
For example, malicious attackers (or just foolish kiddie) may use the feature to make servers down.

Observing the behavior of Codeforces servers, I feel that Codeforces dislike automating submissions.
I know this fact, so I should not do such thing.

## 2. difficulty

Codeforces servers have some tricks to prevent automated submissions, because they don't welcome such submissions.
Cheating such servers is difficult, freaky, and uninteresting.

## 3. benefits

The feature to automate submissions gives users just convenience. It saves only few seconds. That's all.

Considering other features, this is too little benefits.
For example, the features for [random testing](https://github.com/online-judge-tools/oj/blob/master/docs/getting-started.md#random-testing) will save a lot of time and sometimes allows users to solve problems which they cannot solve without such features.
However, automated submissions doesn't have such impact. It's enough to submit by hands.

I know some users likes such convenient (and non-important) features. They might even think this submission feature is the one of main features of our tooling. Maitaining this feature may help earning more users. Howerver, I want to develop my tool for users who use my tool for increasing ratings, not for convenience.

**Comment by lifeModder19135** [comment]
If anything is unethical, it is the "automatically generating solutions" bit. I get that in the context it is perfectly ethical, but for anyone who wants to throw together an answers generator, you've already done most of the work for them.

As far as the argument for the auto-judges being a "tool for malice," it was a great argument... before AWS. That is, before dynamic server space became just as cheap as running your servers on old abandoned Android phones. 

In 2022, if you run out of bandwidth, the fix is... automatic. You do nothing, because the platform does it (the dynamic allocation of extra resources) for you. 

So, so long as you have it configured, bandwidth is infinite, and would-be "hackers" are wasting their time. Unless they have the resources to take down an AWS server site with a brute force DOS attack... in which case, just give up; you're f####d anyway.

Of course, this assumes that CF has dynamically allocated server instances / resources. If not, then I'm sure there are countless other platforms waiting for a chance to take their place at the top.
